In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('first_5_columns.csv', header=None, names=['date', 'time', 'id', 'type', 'component'])
df.head()

    date    time   id  type                     component
0  81109  203518  143  INFO      dfs.DataNode$DataXceiver
1  81109  203518   35  INFO              dfs.FSNamesystem
2  81109  203519  143  INFO      dfs.DataNode$DataXceiver
3  81109  203519  145  INFO      dfs.DataNode$DataXceiver
4  81109  203519  145  INFO  dfs.DataNode$PacketResponder

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11175629 entries, 0 to 11175628
Data columns (total 5 columns):
 #   Column     Dtype
---  ------     -----
 0   date       int64
 1   time       int64
 2   id         int64
 3   type       object
 4   component  object
dtypes: int64(3), object(2)
memory usage: 426.3+ MB

In [4]:
df['id'].value_counts()

19       1288017
28        539758
27        444086
26        441387
30        437971
          ...
120            1
133            1
27863          1
27857          1
37             1
Name: id, Length: 27799, dtype: int64

In [5]:
df['type'].value_counts()

INFO    10812836
WARN      362793
Name: type, dtype: int64

In [6]:
df['row'] = np.arange(1, len(df) + 1)
df.head()

    date    time   id  type                     component  row
0  81109  203518  143  INFO      dfs.DataNode$DataXceiver    1
1  81109  203518   35  INFO              dfs.FSNamesystem    2
2  81109  203519  143  INFO      dfs.DataNode$DataXceiver    3
3  81109  203519  145  INFO      dfs.DataNode$DataXceiver    4
4  81109  203519  145  INFO  dfs.DataNode$PacketResponder    5

In [7]:
y = pd.get_dummies(df['type'], prefix='type')
y.head()

   type_INFO  type_WARN
0          1          0
1          1          0
2          1          0
3          1          0
4          1          0

In [8]:
(sum(y['type_INFO']), sum(y['type_WARN']))

(10812836, 362793)

In [9]:
df['type_INFO'] = y['type_INFO']
df['type_WARN'] = y['type_WARN']
df.drop('type', axis = 1, inplace = True)
df.head()

    date    time   id                     component  row  type_INFO  type_WARN
0  81109  203518  143      dfs.DataNode$DataXceiver    1          1          0
1  81109  203518   35              dfs.FSNamesystem    2          1          0
2  81109  203519  143      dfs.DataNode$DataXceiver    3          1          0
3  81109  203519  145      dfs.DataNode$DataXceiver    4          1          0
4  81109  203519  145  dfs.DataNode$PacketResponder    5          1          0

In [10]:
(sum(df['type_INFO']), sum(df['type_WARN']))

(10812836, 362793)

In [11]:
df['component'].value_counts()

dfs.FSNamesystem                                          3700245
dfs.DataNode$PacketResponder                              3413350
dfs.DataNode$DataXceiver                                  2518678
dfs.FSDataset                                             1407597
dfs.DataBlockScanner                                       120046
dfs.DataNode                                                 7002
dfs.DataNode$DataTransfer                                    6946
dfs.DataNode$BlockReceiver                                   1718
dfs.PendingReplicationBlocks$PendingReplicationMonitor         47
Name: component, dtype: int64

In [12]:
y = pd.get_dummies(df['component'], prefix='comp')
y.head()

,comp_dfs.DataBlockScanner,comp_dfs.DataNode,comp_dfs.DataNode$BlockReceiver,comp_dfs.DataNode$DataTransfer,comp_dfs.DataNode$DataXceiver,comp_dfs.DataNode$PacketResponder,comp_dfs.FSDataset,comp_dfs.FSNamesystem,comp_dfs.PendingReplicationBlocks$PendingReplicationMonitor
0,0,0,0,0,1,0,0,0,0
1,0,0,0,0,0,0,0,1,0
2,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,1,0,0,0

In [13]:
(sum(y['comp_dfs.FSNamesystem']), sum(y['comp_dfs.DataNode$PacketResponder']))

(3700245, 3413350)

In [14]:
df['comp_FSname'] = y['comp_dfs.FSNamesystem']
df['comp_PacketResponder'] = y['comp_dfs.DataNode$PacketResponder']
df['comp_DataXceiver'] = y['comp_dfs.DataNode$DataXceiver']
df['comp_FSDataset'] = y['comp_dfs.FSDataset']
df['comp_DataBlockScanner'] = y['comp_dfs.DataBlockScanner']
df['comp_DataNode'] = y['comp_dfs.DataNode']
df['comp_DataTransfer'] = y['comp_dfs.DataNode$DataTransfer']
df['comp_BlockReceiver'] = y['comp_dfs.DataNode$BlockReceiver']
df['comp_PendingMonitor'] = y['comp_dfs.PendingReplicationBlocks$PendingReplicationMonitor']

df.drop('component', axis = 1, inplace = True)
df.head()

,date,time,id,row,type_INFO,type_WARN,comp_FSname,comp_PacketResponder,comp_DataXceiver,comp_FSDataset,comp_DataBlockScanner,comp_DataNode,comp_DataTransfer,comp_BlockReceiver,comp_PendingMonitor
0,81109,203518,143,1,1,0,0,0,1,0,0,0,0,0,0
1,81109,203518,35,2,1,0,1,0,0,0,0,0,0,0,0
2,81109,203519,143,3,1,0,0,0,1,0,0,0,0,0,0
3,81109,203519,145,4,1,0,0,0,1,0,0,0,0,0,0
4,81109,203519,145,5,1,0,0,1,0,0,0,0,0,0,0

In [15]:
(sum(df['comp_FSname']), sum(df['comp_PacketResponder']))

(3700245, 3413350)

In [16]:
df['date'].value_counts()

81111    5362174
81110    4934076
81109     879379
Name: date, dtype: int64

In [17]:
df.groupby('date').agg({'time': ['min', 'max']})

         time
          min     max
date
81109  203518  235959
81110       0  235959
81111       0  111628

In [18]:
df['time'].head()

0    203518
1    203518
2    203519
3    203519
4    203519
Name: time, dtype: int64

In [19]:
df['hour'] = pd.to_datetime(df['time'], format = '%H%M%S', errors='coerce').dt.hour
df['minute'] = pd.to_datetime(df['time'], format = '%H%M%S', errors='coerce').dt.minute
df['second'] = pd.to_datetime(df['time'], format = '%H%M%S', errors='coerce').dt.second

df.head()

,date,time,id,row,type_INFO,type_WARN,comp_FSname,comp_PacketResponder,comp_DataXceiver,comp_FSDataset,comp_DataBlockScanner,comp_DataNode,comp_DataTransfer,comp_BlockReceiver,comp_PendingMonitor,hour,minute,second
0,81109,203518,143,1,1,0,0,0,1,0,0,0,0,0,0,20.0,35.0,18.0
1,81109,203518,35,2,1,0,1,0,0,0,0,0,0,0,0,20.0,35.0,18.0
2,81109,203519,143,3,1,0,0,0,1,0,0,0,0,0,0,20.0,35.0,19.0
3,81109,203519,145,4,1,0,0,0,1,0,0,0,0,0,0,20.0,35.0,19.0
4,81109,203519,145,5,1,0,0,1,0,0,0,0,0,0,0,20.0,35.0,19.0

In [20]:
df['seconds'] = ((df['date'] - 81109) * 86400) + (df['hour'] * 3600) + (df['minute'] * 60) + df['second']

df.drop('date', axis = 1, inplace = True)
df.drop('time', axis = 1, inplace = True)
df.drop('hour', axis = 1, inplace = True)
df.drop('minute', axis = 1, inplace = True)
df.drop('second', axis = 1, inplace = True)

df.head()

,id,row,type_INFO,type_WARN,comp_FSname,comp_PacketResponder,comp_DataXceiver,comp_FSDataset,comp_DataBlockScanner,comp_DataNode,comp_DataTransfer,comp_BlockReceiver,comp_PendingMonitor,seconds
0,143,1,1,0,0,0,1,0,0,0,0,0,0,74118.0
1,35,2,1,0,1,0,0,0,0,0,0,0,0,74118.0
2,143,3,1,0,0,0,1,0,0,0,0,0,0,74119.0
3,145,4,1,0,0,0,1,0,0,0,0,0,0,74119.0
4,145,5,1,0,0,1,0,0,0,0,0,0,0,74119.0

In [21]:
df['seconds'].fillna(method='ffill', inplace=True)

In [22]:
df['seconds'].isnull().sum()

0

In [23]:
df['minutes'] = (df['seconds'] // 60).astype('int')
df.drop('seconds', axis = 1, inplace = True)
df.drop('id', axis = 1, inplace = True)
df.head()

,row,type_INFO,type_WARN,comp_FSname,comp_PacketResponder,comp_DataXceiver,comp_FSDataset,comp_DataBlockScanner,comp_DataNode,comp_DataTransfer,comp_BlockReceiver,comp_PendingMonitor,minutes
0,1,1,0,0,0,1,0,0,0,0,0,0,1235
1,2,1,0,1,0,0,0,0,0,0,0,0,1235
2,3,1,0,0,0,1,0,0,0,0,0,0,1235
3,4,1,0,0,0,1,0,0,0,0,0,0,1235
4,5,1,0,0,1,0,0,0,0,0,0,0,1235

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11175629 entries, 0 to 11175628
Data columns (total 13 columns):
 #   Column                 Dtype
---  ------                 -----
 0   row                    int32
 1   type_INFO              uint8
 2   type_WARN              uint8
 3   comp_FSname            uint8
 4   comp_PacketResponder   uint8
 5   comp_DataXceiver       uint8
 6   comp_FSDataset         uint8
 7   comp_DataBlockScanner  uint8
 8   comp_DataNode          uint8
 9   comp_DataTransfer      uint8
 10  comp_BlockReceiver     uint8
 11  comp_PendingMonitor    uint8
 12  minutes                int32
dtypes: int32(2), uint8(11)
memory usage: 202.5 MB

In [25]:
df.to_csv('processed_01.csv', index=False, header=True)